<h3>Menu</h3>
<ul>
    <li>
        <a href="<?php echo $this->url(array(), 'book-admin'); ?>">Index</a>
    </li>
    <li>
        <a href="<?php echo $this->url(array(), 'book-review-latest'); ?>">Latest Review</a>
    </li>
    <li>
        <a href="<?php echo $this->url(array(), 'book-insert'); ?>">Insert New Book</a>
    </li>
    <li>
        <a href="<?php echo $this->url(array(), 'book-insert-author'); ?>">Authors</a>
    </li>
    <li>
        <a href="<?php echo $this->url(array(), 'book-insert-category'); ?>">Categories</a>
    </li>
    <li>
        <a href="<?php echo $this->url(array(), 'book-insert-publisher'); ?>">Publishers</a>
    </li>
    <li>
        <a href="<?php echo $this->url(array(), 'book-flushcache'); ?>">Flush All Cache</a>
    </li>
</ul>