<?php $this->headTitle($this->book->book_title); ?>
<div class="grid_3 book_list radius_10 left">
    <ul>
        <div class="book_cover">
            <img src="<?php echo $this->book->cover_filepath; ?>" alt="<?php echo $this->book->book_title; ?>" />
        </div>
        <li>
            <span>Author: </span> <br />
            <a href="<?php echo $this->url(array('id_author' => $this->book->id_books_author), 'book-author'); ?>"><?php echo $this->escape($this->book->BooksAuthor->author_name); ?></a>
        </li>
        <li>
            <span>Category: </span> <br />
            <a href="<?php echo $this->url(array('id_category' => $this->book->id_books_category), 'book-category'); ?>"><?php echo $this->escape($this->book->BooksCategory->category_name); ?></a>
        </li>
        <li>
            <span>Publisher: </span> <br />
            <a href="<?php echo $this->url(array('id_publisher' => $this->book->id_books_publisher), 'book-publisher'); ?>"><?php echo $this->escape($this->book->BooksPublisher->publisher_name); ?></a>
        </li>
        <li>
            <span>Year Published: </span> <br />
            <?php echo $this->escape($this->book->year_published); ?>
        </li>
        <li>
            <span>ISBN: </span> <br />
            <?php echo ($this->book->isbn) ? $this->escape($this->book->isbn) : 'N/A'; ?>
        </li>
        <?php if ($this->getService('Book_Service_Book')->checkAcl('manage')) : ?>
        <li>
            <span>Manage: </span> <br />
            <a href="<?php echo $this->url(array('id_book' => $this->book->id_books), 'book-update'); ?>">Edit This Book</a>
        </li>
        <?php endif; ?>
    </ul>
</div>
<div class="grid_9 book_detail radius_10 right">
    <h1>
        <?php echo $this->escape($this->book->book_title); ?>
    </h1>
    <div class="book_detail_content">
        <p>
            <?php echo nl2br($this->book->book_abstract); ?>
        </p>
        
        <h3 class="radius_5">Review(s)</h3>
        <?php if ($this->book->BooksReview->count() !== 0): ?>
        <ul>
        <?php foreach ($this->book->BooksReview as $review) : ?>
            <li class="radius_10">
                <div class="gravatar left">
                    <?php echo $this->gravatar($review->email, array('img_size' => 48), array('alt' => 'reviewer\'s gravatar', 'class' => 'radius_5')); ?>
                </div>
                <p>
                    <span><?php echo $this->escape($review->name); ?> - <?php echo new Zend_Date($review->review_time); ?></span> <br>
                    <?php echo nl2br($review->content); ?>
                    <?php if ($this->getService('Book_Service_Review')->checkAcl('delete')) : ?>
                    <br />
                    <a href="#">Delete This Review</a>
                    <?php endif; ?>
                </p>
            </li>
        <?php endforeach; ?>
        </ul>
        <?php endif;?>
        
        <h4>Review Form</h4>
        <?php echo $this->review_form; ?>
    </div>
</div>